version: '3'
services:
  server:
    container_name: server
    build:
      context: ./backend-web
    expose:
      - 8080
    environment:
      - TZ=Asia/Seoul
  client:
    container_name: client
    build:
      context: ./frontend-web
    expose:
      - 3000
    depends_on:
      - server
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    restart: always
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - client
    ports:
      - 80:80
      - 443:443