version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend-web
      args:
        SERVER_MODE: dev
    ports:
      - 8081:8080
  frontend:
    container_name: frontend
    build:
      context: ./frontend-web
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    depends_on:
      - backend