version: '3'

networks:
  server-connection:
    driver: bridge

services:
  server:
    container_name: server
    networks:
      - server-connection
    build:
      context: ./backend-web
    expose:
      - 8080
    environment:
      - TZ=Asia/Seoul
  client:
    container_name: client
    networks:
      - server-connection
    build:
      context: ./frontend-web
    expose:
      - 3000
    depends_on:
      - server
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    restart: always
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - client
    ports:
      - 80:80
      - 443:443