spring:
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://sonagi.site:50000/ssafy_b207?characterEncoding=UTF-8
    username: ssafy-b207
    password: ssafy_b207_1

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ssafy
    key-store-type: PKCS12